version: "3"

services:
    db:
        image: mysql:8.0.33
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            ## He cambiado el puerto porque ya tengo un proyecto usando el 3306:3306 por defecto
        ports:
            - 3307:3306
        networks:
            - symfony_app
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/symfony:cached
            - symfony_app_var:/var/www/symfony/var
            - symfony_app_vendor:/var/www/symfony/vendor
        networks:
            - symfony_app
    nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/symfony:cached
            - symfony_app_var:/var/www/symfony/var
            - symfony_app_vendor:/var/www/symfony/vendor
             ## He cambiado el puerto porque ya tengo un proyecto usando el 8081:8080 por defecto
        ports:
            - 81:80
        networks:
            - symfony_app
        env_file:
            - .env.nginx.local

volumes:
    symfony_app_var:
    symfony_app_vendor:
    db_app:

networks:
    symfony_app:
